### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by foxdon13** [wsvincent/djangoforprofessionals_30#1]
In chapter 1, after building up the docker, when docker-compose up command is run we get an error as follows:
```
Creating network "hello_default" with the default driver
Creating hello_web_1 ... done
Attaching to hello_web_1
web_1  | Traceback (most recent call last):
web_1  |   File "/code/manage.py", line 10, in main
web_1  |     from django.core.management import execute_from_command_line
web_1  | ModuleNotFoundError: No module named 'django'
web_1  | 
web_1  | The above exception was the direct cause of the following exception:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/code/manage.py", line 21, in <module>
web_1  |     main()
web_1  |   File "/code/manage.py", line 16, in main
web_1  |     ) from exc
web_1  | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
hello_web_1 exited with code 1

```

**Comment by foxdon13** [comment]
Solved it using docker-compose build .
